-- --------------------------------------------------------------------------------
-- -- Proyecto: Sistema de Gestión de Asistencia Estudiantil (SGAE)
-- -- Versión: 2.0 (Propuesta Moderna)
-- -- Autor: [Su Nombre/Equipo de Desarrollo] con mejoras de arquitectura
-- -- Fecha de Creación: 14-09-2025
-- -- Motor de BD: Oracle
-- --
-- -- Descripción: Script DDL modernizado para la aplicación SGAE.
-- -- MEJORAS CLAVE:
-- -- 1. IDs Autoincrementales Nativos: Se utiliza 'GENERATED AS IDENTITY' en lugar
-- --    de secuencias y triggers, simplificando drásticamente el código.
-- -- 2. Lógica de QR Integrada: Se añaden las tablas y lógica necesarias para el
-- --    registro de asistencia mediante códigos QR (entrada/salida).
-- -- 3. Auditoría Genérica y Reutilizable: Se implementa un único procedimiento
-- --    almacenado para auditar cualquier tabla, haciendo el sistema más mantenible.
-- --------------------------------------------------------------------------------

SPOOL creacion_bd_sgae_moderno.log

-- --------------------------------------------------------------------------------
-- SECCIÓN 1: ELIMINACIÓN DE OBJETOS EXISTENTES
-- --------------------------------------------------------------------------------
-- Descripción: Garantiza un entorno limpio para cada ejecución del script.
PROMPT Eliminando objetos existentes...
DECLARE
    -- Este bloque PL/SQL elimina en orden: procedimientos, vistas y tablas.
BEGIN
    FOR rec IN (SELECT object_name, object_type FROM user_objects WHERE object_type IN ('PROCEDURE', 'VIEW', 'TABLE')) LOOP
        IF rec.object_type = 'PROCEDURE' THEN
            EXECUTE IMMEDIATE 'DROP PROCEDURE ' || rec.object_name;
        ELSIF rec.object_type = 'VIEW' THEN
            EXECUTE IMMEDIATE 'DROP VIEW ' || rec.object_name;
        ELSIF rec.object_type = 'TABLE' THEN
            EXECUTE IMMEDIATE 'DROP TABLE ' || rec.object_name || ' CASCADE CONSTRAINTS';
        END IF;
    END LOOP;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('No se encontraron objetos para eliminar o ocurrió un error menor.');
END;
/

-- --------------------------------------------------------------------------------
-- SECCIÓN 2: CREACIÓN DE TABLAS CON IDs MODERNOS
-- --------------------------------------------------------------------------------
-- Descripción: Se definen las tablas utilizando 'GENERATED BY DEFAULT AS IDENTITY'
-- para las claves primarias. Esto elimina la necesidad de crear secuencias y
-- triggers para cada tabla, resultando en un esquema más limpio y moderno.
PROMPT Creando tablas...

-- Tablas de Catálogo
CREATE TABLE FACULTADES (
    ID_FACULTAD         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NOMBRE_FACULTAD     VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_FACULTADES PRIMARY KEY (ID_FACULTAD),
    CONSTRAINT UQ_FACULTADES_NOMBRE UNIQUE (NOMBRE_FACULTAD)
);

CREATE TABLE CARRERAS (
    ID_CARRERA          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ID_FACULTAD_FK      NUMBER NOT NULL,
    NOMBRE_CARRERA      VARCHAR2(150) NOT NULL,
    CONSTRAINT PK_CARRERAS PRIMARY KEY (ID_CARRERA),
    CONSTRAINT UQ_CARRERAS_NOMBRE UNIQUE (NOMBRE_CARRERA)
);

CREATE TABLE ESTUDIANTES (
    ID_ESTUDIANTE       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ID_CARRERA_FK       NUMBER NOT NULL,
    NUMERO_CARNET       VARCHAR2(20) NOT NULL,
    NOMBRES             VARCHAR2(100) NOT NULL,
    APELLIDOS           VARCHAR2(100) NOT NULL,
    EMAIL               VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_ESTUDIANTES PRIMARY KEY (ID_ESTUDIANTE),
    CONSTRAINT UQ_ESTUDIANTES_CARNET UNIQUE (NUMERO_CARNET),
    CONSTRAINT UQ_ESTUDIANTES_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE CATEDRATICOS (
    ID_CATEDRATICO      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    CODIGO_EMPLEADO     VARCHAR2(20) NOT NULL,
    NOMBRES             VARCHAR2(100) NOT NULL,
    APELLIDOS           VARCHAR2(100) NOT NULL,
    EMAIL_INSTITUCIONAL VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_CATEDRATICOS PRIMARY KEY (ID_CATEDRATICO),
    CONSTRAINT UQ_CATEDRATICOS_CODIGO UNIQUE (CODIGO_EMPLEADO),
    CONSTRAINT UQ_CATEDRATICOS_EMAIL UNIQUE (EMAIL_INSTITUCIONAL)
);

CREATE TABLE USUARIOS (
    ID_USUARIO          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ID_ESTUDIANTE_FK    NUMBER,
    ID_CATEDRATICO_FK   NUMBER,
    NOMBRE_USUARIO      VARCHAR2(50) NOT NULL,
    CONTRASENA_HASH     VARCHAR2(256) NOT NULL,
    TIPO_USUARIO        VARCHAR2(15) NOT NULL,
    ESTADO              CHAR(1) DEFAULT 'A' NOT NULL,
    FECHA_CREACION      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_USUARIOS PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UQ_USUARIOS_NOMBRE UNIQUE (NOMBRE_USUARIO),
    CONSTRAINT CK_USUARIOS_TIPO CHECK (TIPO_USUARIO IN ('ESTUDIANTE', 'CATEDRATICO', 'ADMIN')),
    CONSTRAINT CK_USUARIOS_ESTADO CHECK (ESTADO IN ('A', 'I')),
    CONSTRAINT CK_USUARIOS_FK_EXCLUSIVA CHECK (
        (ID_ESTUDIANTE_FK IS NOT NULL AND ID_CATEDRATICO_FK IS NULL AND TIPO_USUARIO = 'ESTUDIANTE') OR
        (ID_ESTUDIANTE_FK IS NULL AND ID_CATEDRATICO_FK IS NOT NULL AND TIPO_USUARIO = 'CATEDRATICO') OR
        (ID_ESTUDIANTE_FK IS NULL AND ID_CATEDRATICO_FK IS NULL AND TIPO_USUARIO = 'ADMIN')
    )
);

CREATE TABLE PERIODOS_ACADEMICOS (
    ID_PERIODO          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NOMBRE_PERIODO      VARCHAR2(50) NOT NULL,
    FECHA_INICIO        DATE NOT NULL,
    FECHA_FIN           DATE NOT NULL,
    ESTADO              CHAR(1) DEFAULT 'A' NOT NULL,
    CONSTRAINT PK_PERIODOS_ACADEMICOS PRIMARY KEY (ID_PERIODO),
    CONSTRAINT UQ_PERIODOS_NOMBRE UNIQUE (NOMBRE_PERIODO),
    CONSTRAINT CK_PERIODOS_ESTADO CHECK (ESTADO IN ('A', 'I', 'C')) -- Activo, Inactivo, Cerrado
);

CREATE TABLE CURSOS (
    ID_CURSO            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    CODIGO_CURSO        VARCHAR2(15) NOT NULL,
    NOMBRE_CURSO        VARCHAR2(150) NOT NULL,
    CREDITOS            NUMBER(2) NOT NULL,
    CONSTRAINT PK_CURSOS PRIMARY KEY (ID_CURSO),
    CONSTRAINT UQ_CURSOS_CODIGO UNIQUE (CODIGO_CURSO)
);

CREATE TABLE AULAS (
    ID_AULA             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    CODIGO_AULA         VARCHAR2(20) NOT NULL,
    EDIFICIO            VARCHAR2(50),
    CAPACIDAD           NUMBER(3),
    CONSTRAINT PK_AULAS PRIMARY KEY (ID_AULA),
    CONSTRAINT UQ_AULAS_CODIGO UNIQUE (CODIGO_AULA)
);

CREATE TABLE SECCIONES (
    ID_SECCION          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    CODIGO_SECCION      VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_SECCIONES PRIMARY KEY (ID_SECCION),
    CONSTRAINT UQ_SECCIONES_CODIGO UNIQUE (CODIGO_SECCION)
);

-- Tablas Transaccionales
CREATE TABLE CURSOS_IMPARTIDOS (
    ID_CURSO_IMPARTIDO  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ID_CURSO_FK         NUMBER NOT NULL,
    ID_CATEDRATICO_FK   NUMBER NOT NULL,
    ID_SECCION_FK       NUMBER NOT NULL,
    ID_PERIODO_FK       NUMBER NOT NULL,
    ID_AULA_FK          NUMBER NOT NULL,
    HORARIO             VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_CURSOS_IMPARTIDOS PRIMARY KEY (ID_CURSO_IMPARTIDO)
);

CREATE TABLE INSCRIPCIONES (
    ID_INSCRIPCION          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ID_ESTUDIANTE_FK        NUMBER NOT NULL,
    ID_CURSO_IMPARTIDO_FK   NUMBER NOT NULL,
    FECHA_INSCRIPCION       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_INSCRIPCIONES PRIMARY KEY (ID_INSCRIPCION),
    CONSTRAINT UQ_INSCRIPCION_UNICA UNIQUE (ID_ESTUDIANTE_FK, ID_CURSO_IMPARTIDO_FK)
);

-- MEJORA: Tabla adaptada para la lógica de Entrada/Salida por QR.
CREATE TABLE REGISTROS_ASISTENCIA (
    ID_REGISTRO             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ID_INSCRIPCION_FK       NUMBER NOT NULL,
    FECHA_HORA_REGISTRO     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    TIPO_REGISTRO           VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_REGISTROS_ASISTENCIA PRIMARY KEY (ID_REGISTRO),
    CONSTRAINT CK_TIPO_REGISTRO CHECK (TIPO_REGISTRO IN ('ENTRADA', 'SALIDA'))
);

-- NUEVA TABLA: Almacena los códigos únicos para cada sesión de clase.
CREATE TABLE SESIONES_CLASE_QR (
    ID_SESION_QR            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ID_CURSO_IMPARTIDO_FK   NUMBER NOT NULL,
    CODIGO_QR               VARCHAR2(255) NOT NULL,
    FECHA_CREACION          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ESTADO                  CHAR(1) DEFAULT 'A' NOT NULL,
    CONSTRAINT PK_SESIONES_CLASE_QR PRIMARY KEY (ID_SESION_QR),
    CONSTRAINT UQ_SESIONES_CLASE_QR_CODIGO UNIQUE (CODIGO_QR),
    CONSTRAINT CK_SESIONES_CLASE_QR_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

-- MEJORA: Tabla de Auditoría
CREATE TABLE AUDITORIA (
    ID_AUDITORIA            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NOMBRE_TABLA            VARCHAR2(30) NOT NULL,
    ID_REGISTRO_AFECTADO    VARCHAR2(100),
    TIPO_ACCION             VARCHAR2(10) NOT NULL, -- INSERT, UPDATE, DELETE
    VALORES_ANTERIORES      CLOB,
    VALORES_NUEVOS          CLOB,
    USUARIO_APP             VARCHAR2(100), -- Usuario de la aplicación (pasado desde el backend)
    USUARIO_BD              VARCHAR2(100) DEFAULT USER NOT NULL,
    FECHA_ACCION            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_AUDITORIA PRIMARY KEY (ID_AUDITORIA),
    CONSTRAINT CK_AUDITORIA_TIPO_ACCION CHECK (TIPO_ACCION IN ('INSERT', 'UPDATE', 'DELETE'))
);


-- --------------------------------------------------------------------------------
-- SECCIÓN 3: CREACIÓN DE CONSTRAINTS (FOREIGN KEYS)
-- --------------------------------------------------------------------------------
PROMPT Creando Foreign Keys...
ALTER TABLE CARRERAS ADD CONSTRAINT FK_CARRERAS_FACULTAD FOREIGN KEY (ID_FACULTAD_FK) REFERENCES FACULTADES(ID_FACULTAD);
ALTER TABLE ESTUDIANTES ADD CONSTRAINT FK_ESTUDIANTES_CARRERA FOREIGN KEY (ID_CARRERA_FK) REFERENCES CARRERAS(ID_CARRERA);
ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_ESTUDIANTE FOREIGN KEY (ID_ESTUDIANTE_FK) REFERENCES ESTUDIANTES(ID_ESTUDIANTE) ON DELETE SET NULL;
ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_CATEDRATICO FOREIGN KEY (ID_CATEDRATICO_FK) REFERENCES CATEDRATICOS(ID_CATEDRATICO) ON DELETE SET NULL;
ALTER TABLE CURSOS_IMPARTIDOS ADD CONSTRAINT FK_CI_CURSO FOREIGN KEY (ID_CURSO_FK) REFERENCES CURSOS(ID_CURSO);
ALTER TABLE CURSOS_IMPARTIDOS ADD CONSTRAINT FK_CI_CATEDRATICO FOREIGN KEY (ID_CATEDRATICO_FK) REFERENCES CATEDRATICOS(ID_CATEDRATICO);
ALTER TABLE CURSOS_IMPARTIDOS ADD CONSTRAINT FK_CI_SECCION FOREIGN KEY (ID_SECCION_FK) REFERENCES SECCIONES(ID_SECCION);
ALTER TABLE CURSOS_IMPARTIDOS ADD CONSTRAINT FK_CI_PERIODO FOREIGN KEY (ID_PERIODO_FK) REFERENCES PERIODOS_ACADEMICOS(ID_PERIODO);
ALTER TABLE CURSOS_IMPARTIDOS ADD CONSTRAINT FK_CI_AULA FOREIGN KEY (ID_AULA_FK) REFERENCES AULAS(ID_AULA);
ALTER TABLE INSCRIPCIONES ADD CONSTRAINT FK_INSCRIPCIONES_ESTUDIANTE FOREIGN KEY (ID_ESTUDIANTE_FK) REFERENCES ESTUDIANTES(ID_ESTUDIANTE);
ALTER TABLE INSCRIPCIONES ADD CONSTRAINT FK_INSCRIPCIONES_CI FOREIGN KEY (ID_CURSO_IMPARTIDO_FK) REFERENCES CURSOS_IMPARTIDOS(ID_CURSO_IMPARTIDO);
ALTER TABLE REGISTROS_ASISTENCIA ADD CONSTRAINT FK_RA_INSCRIPCION FOREIGN KEY (ID_INSCRIPCION_FK) REFERENCES INSCRIPCIONES(ID_INSCRIPCION) ON DELETE CASCADE;
ALTER TABLE SESIONES_CLASE_QR ADD CONSTRAINT FK_SCQR_CI FOREIGN KEY (ID_CURSO_IMPARTIDO_FK) REFERENCES CURSOS_IMPARTIDOS(ID_CURSO_IMPARTIDO);

-- --------------------------------------------------------------------------------
-- SECCIÓN 4: CREACIÓN DE ÍNDICES
-- --------------------------------------------------------------------------------
PROMPT Creando Índices para optimización de consultas...
-- Índices en todas las claves foráneas
CREATE INDEX IDX_CARRERAS_FACULTAD_FK ON CARRERAS(ID_FACULTAD_FK);
CREATE INDEX IDX_ESTUDIANTES_CARRERA_FK ON ESTUDIANTES(ID_CARRERA_FK);
CREATE INDEX IDX_USUARIOS_ESTUDIANTE_FK ON USUARIOS(ID_ESTUDIANTE_FK);
CREATE INDEX IDX_USUARIOS_CATEDRATICO_FK ON USUARIOS(ID_CATEDRATICO_FK);
CREATE INDEX IDX_CI_CURSO_FK ON CURSOS_IMPARTIDOS(ID_CURSO_FK);
CREATE INDEX IDX_CI_CATEDRATICO_FK ON CURSOS_IMPARTIDOS(ID_CATEDRATICO_FK);
CREATE INDEX IDX_CI_SECCION_FK ON CURSOS_IMPARTIDOS(ID_SECCION_FK);
CREATE INDEX IDX_CI_PERIODO_FK ON CURSOS_IMPARTIDOS(ID_PERIODO_FK);
CREATE INDEX IDX_CI_AULA_FK ON CURSOS_IMPARTIDOS(ID_AULA_FK);
CREATE INDEX IDX_INS_ESTUDIANTE_FK ON INSCRIPCIONES(ID_ESTUDIANTE_FK);
CREATE INDEX IDX_INS_CI_FK ON INSCRIPCIONES(ID_CURSO_IMPARTIDO_FK);
CREATE INDEX IDX_RA_INSCRIPCION_FK ON REGISTROS_ASISTENCIA(ID_INSCRIPCION_FK);
CREATE INDEX IDX_SCQR_CI_FK ON SESIONES_CLASE_QR(ID_CURSO_IMPARTIDO_FK);
-- Índice para búsqueda por código QR
CREATE INDEX IDX_SCQR_CODIGO_QR ON SESIONES_CLASE_QR(CODIGO_QR);

-- --------------------------------------------------------------------------------
-- SECCIÓN 5: CREACIÓN DE VISTAS
-- --------------------------------------------------------------------------------
PROMPT Creando vistas para simplificar consultas...
CREATE OR REPLACE VIEW V_REPORTE_ASISTENCIA_DIARIA AS
SELECT
    TRUNC(RA.FECHA_HORA_REGISTRO) AS FECHA,
    E.NUMERO_CARNET,
    E.NOMBRES || ' ' || E.APELLIDOS AS NOMBRE_ESTUDIANTE,
    C.NOMBRE_CURSO,
    S.CODIGO_SECCION,
    (SELECT FECHA_HORA_REGISTRO FROM REGISTROS_ASISTENCIA WHERE ID_INSCRIPCION_FK = I.ID_INSCRIPCION AND TIPO_REGISTRO = 'ENTRADA' AND TRUNC(FECHA_HORA_REGISTRO) = TRUNC(RA.FECHA_HORA_REGISTRO)) AS HORA_ENTRADA,
    (SELECT FECHA_HORA_REGISTRO FROM REGISTROS_ASISTENCIA WHERE ID_INSCRIPCION_FK = I.ID_INSCRIPCION AND TIPO_REGISTRO = 'SALIDA' AND TRUNC(FECHA_HORA_REGISTRO) = TRUNC(RA.FECHA_HORA_REGISTRO)) AS HORA_SALIDA,
    CAT.NOMBRES || ' ' || CAT.APELLIDOS AS NOMBRE_CATEDRATICO,
    P.NOMBRE_PERIODO
FROM REGISTROS_ASISTENCIA RA
JOIN INSCRIPCIONES I ON RA.ID_INSCRIPCION_FK = I.ID_INSCRIPCION
JOIN ESTUDIANTES E ON I.ID_ESTUDIANTE_FK = E.ID_ESTUDIANTE
JOIN CURSOS_IMPARTIDOS CI ON I.ID_CURSO_IMPARTIDO_FK = CI.ID_CURSO_IMPARTIDO
JOIN CURSOS C ON CI.ID_CURSO_FK = C.ID_CURSO
JOIN SECCIONES S ON CI.ID_SECCION_FK = S.ID_SECCION
JOIN CATEDRATICOS CAT ON CI.ID_CATEDRATICO_FK = CAT.ID_CATEDRATICO
JOIN PERIODOS_ACADEMICOS P ON CI.ID_PERIODO_FK = P.ID_PERIODO
GROUP BY TRUNC(RA.FECHA_HORA_REGISTRO), I.ID_INSCRIPCION, E.NUMERO_CARNET, E.NOMBRES, E.APELLIDOS, C.NOMBRE_CURSO, S.CODIGO_SECCION, CAT.NOMBRES, CAT.APELLIDOS, P.NOMBRE_PERIODO;

-- --------------------------------------------------------------------------------
-- SECCIÓN 6: CREACIÓN DE PROCEDIMIENTOS ALMACENADOS
-- --------------------------------------------------------------------------------
PROMPT Creando procedimientos almacenados para la lógica de negocio...
-- MEJORA: Procedimiento adaptado a la lógica de negocio del QR.
CREATE OR REPLACE PROCEDURE SP_REGISTRAR_ASISTENCIA (
    p_codigo_qr           IN VARCHAR2,
    p_numero_carnet       IN VARCHAR2,
    p_tipo_registro       IN VARCHAR2, -- 'ENTRADA' o 'SALIDA'
    p_resultado           OUT VARCHAR2,
    p_detalle             OUT VARCHAR2
) AS
    v_id_estudiante         NUMBER;
    v_id_curso_impartido    NUMBER;
    v_id_inscripcion        NUMBER;
    v_conteo_entrada        NUMBER;
    v_conteo_salida         NUMBER;
BEGIN
    -- 1. Validar el código QR y obtener el curso impartido
    BEGIN
        SELECT ID_CURSO_IMPARTIDO_FK INTO v_id_curso_impartido
        FROM SESIONES_CLASE_QR
        WHERE CODIGO_QR = p_codigo_qr AND ESTADO = 'A';
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            p_resultado := 'ERROR';
            p_detalle := 'Código QR inválido o expirado.';
            RETURN;
    END;

    -- 2. Obtener ID del estudiante
    BEGIN
        SELECT ID_ESTUDIANTE INTO v_id_estudiante FROM ESTUDIANTES WHERE NUMERO_CARNET = p_numero_carnet;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            p_resultado := 'ERROR';
            p_detalle := 'Número de carnet no encontrado.';
            RETURN;
    END;

    -- 3. Obtener ID de la inscripción
    BEGIN
        SELECT ID_INSCRIPCION INTO v_id_inscripcion
        FROM INSCRIPCIONES
        WHERE ID_ESTUDIANTE_FK = v_id_estudiante
          AND ID_CURSO_IMPARTIDO_FK = v_id_curso_impartido;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            p_resultado := 'ERROR';
            p_detalle := 'El estudiante no está inscrito en este curso.';
            RETURN;
    END;

    -- 4. Aplicar lógica de Entrada/Salida
    SELECT COUNT(*) INTO v_conteo_entrada
    FROM REGISTROS_ASISTENCIA
    WHERE ID_INSCRIPCION_FK = v_id_inscripcion
      AND TRUNC(FECHA_HORA_REGISTRO) = TRUNC(SYSDATE)
      AND TIPO_REGISTRO = 'ENTRADA';

    SELECT COUNT(*) INTO v_conteo_salida
    FROM REGISTROS_ASISTENCIA
    WHERE ID_INSCRIPCION_FK = v_id_inscripcion
      AND TRUNC(FECHA_HORA_REGISTRO) = TRUNC(SYSDATE)
      AND TIPO_REGISTRO = 'SALIDA';

    IF p_tipo_registro = 'ENTRADA' THEN
        IF v_conteo_entrada > 0 THEN
            p_resultado := 'AVISO';
            p_detalle := 'La entrada ya fue registrada para hoy.';
            RETURN;
        END IF;
    ELSIF p_tipo_registro = 'SALIDA' THEN
        IF v_conteo_entrada = 0 THEN
            p_resultado := 'ERROR';
            p_detalle := 'Debe registrar una entrada antes de registrar una salida.';
            RETURN;
        END IF;
        IF v_conteo_salida > 0 THEN
            p_resultado := 'AVISO';
            p_detalle := 'La salida ya fue registrada para hoy.';
            RETURN;
        END IF;
    ELSE
        p_resultado := 'ERROR';
        p_detalle := 'Tipo de registro inválido.';
        RETURN;
    END IF;

    -- 5. Insertar el registro
    INSERT INTO REGISTROS_ASISTENCIA (ID_INSCRIPCION_FK, TIPO_REGISTRO)
    VALUES (v_id_inscripcion, p_tipo_registro);

    COMMIT;
    p_resultado := 'EXITO';
    p_detalle := 'Registro de ' || p_tipo_registro || ' guardado correctamente.';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_resultado := 'ERROR';
        p_detalle := 'Ocurrió un error inesperado: ' || SQLERRM;
END;
/

-- --------------------------------------------------------------------------------
-- SECCIÓN 7: MÓDULO DE AUDITORÍA GENÉRICO
-- --------------------------------------------------------------------------------
-- Descripción: En lugar de un trigger por tabla, se crea un único procedimiento
-- que puede auditar CUALQUIER tabla. Los triggers se vuelven simples y solo se
-- encargan de llamar a este procedimiento, haciendo el sistema mucho más fácil
-- de mantener y extender.
PROMPT Creando módulo de auditoría genérico...
CREATE OR REPLACE PROCEDURE SP_AUDITAR_TABLA (
    p_nombre_tabla       IN VARCHAR2,
    p_tipo_accion        IN VARCHAR2,
    p_id_registro        IN VARCHAR2,
    p_valores_anteriores IN CLOB,
    p_valores_nuevos     IN CLOB,
    p_usuario_app        IN VARCHAR2 DEFAULT NULL
) AS
BEGIN
    INSERT INTO AUDITORIA (
        NOMBRE_TABLA,
        ID_REGISTRO_AFECTADO,
        TIPO_ACCION,
        VALORES_ANTERIORES,
        VALORES_NUEVOS,
        USUARIO_APP
    ) VALUES (
        p_nombre_tabla,
        p_id_registro,
        p_tipo_accion,
        p_valores_anteriores,
        p_valores_nuevos,
        p_usuario_app
    );
END;
/

-- --------------------------------------------------------------------------------
-- SECCIÓN 8: TRIGGERS DE AUDITORÍA SIMPLIFICADOS
-- --------------------------------------------------------------------------------
-- Descripción: Estos triggers ahora son muy simples. Su única responsabilidad
-- es recolectar la información del cambio y llamar al procedimiento genérico
-- SP_AUDITAR_TABLA.
PROMPT Creando triggers de auditoría...

CREATE OR REPLACE TRIGGER TRG_AUD_ESTUDIANTES
AFTER INSERT OR UPDATE OR DELETE ON ESTUDIANTES
FOR EACH ROW
DECLARE
    v_tipo_accion       VARCHAR2(10);
    v_valores_antiguos  CLOB;
    v_valores_nuevos    CLOB;
BEGIN
    IF INSERTING THEN
        v_tipo_accion := 'INSERT';
        v_valores_nuevos := 'CARNET: ' || :NEW.NUMERO_CARNET || ', NOMBRES: ' || :NEW.NOMBRES;
    ELSIF UPDATING THEN
        v_tipo_accion := 'UPDATE';
        v_valores_antiguos := 'CARNET: ' || :OLD.NUMERO_CARNET || ', NOMBRES: ' || :OLD.NOMBRES;
        v_valores_nuevos := 'CARNET: ' || :NEW.NUMERO_CARNET || ', NOMBRES: ' || :NEW.NOMBRES;
    ELSIF DELETING THEN
        v_tipo_accion := 'DELETE';
        v_valores_antiguos := 'CARNET: ' || :OLD.NUMERO_CARNET || ', NOMBRES: ' || :OLD.NOMBRES;
    END IF;

    SP_AUDITAR_TABLA(
        p_nombre_tabla => 'ESTUDIANTES',
        p_tipo_accion => v_tipo_accion,
        p_id_registro => NVL(TO_CHAR(:NEW.ID_ESTUDIANTE), TO_CHAR(:OLD.ID_ESTUDIANTE)),
        p_valores_anteriores => v_valores_antiguos,
        p_valores_nuevos => v_valores_nuevos
    );
END;
/

CREATE OR REPLACE TRIGGER TRG_AUD_REGISTROS_ASISTENCIA
AFTER INSERT ON REGISTROS_ASISTENCIA
FOR EACH ROW
BEGIN
    SP_AUDITAR_TABLA(
        p_nombre_tabla => 'REGISTROS_ASISTENCIA',
        p_tipo_accion => 'INSERT',
        p_id_registro => :NEW.ID_REGISTRO,
        p_valores_nuevos => 'INSCRIPCION_FK: ' || :NEW.ID_INSCRIPCION_FK || ', TIPO: ' || :NEW.TIPO_REGISTRO
    );
END;
/

PROMPT Proceso de creación de base de datos finalizado.
SPOOL OFF
